### ISSUE TITLE
[Firebase OAuth 로그인] 프론트/백 병합 시 신규 가입이 안되는 문제

### ISSUE THREAD

**Issue by jieun-dev1** [Couch-Coders/6th-music-fe#3]
원인: 

(1) Auth.ts 의 user 코드를 firebaseAuth 에서 가져왔는데 이는 백엔드 서버에서 오는 user 랑은 다른 것이다. 
 setUser를 해줬는데, 이는 로그인 된 유저를 전체에 저장하는 코드다.상단에 사용했던 유저는 FirebaseUser 이기 때문에 제대로 저장이 안된 것 (이는 토큰 반환 위한 인증에만 사용하는 용도였음)
-> 해당 코드는 getIdToken 까지의 역할만 한다. 따라서 FireaseAuth는 FirebaseAuthUser라고 변수를 변경해주고, token 받아온 이후에는 user 를 따로 선언해주자. 

(2) 200 일 때와, 404 일 때 분기 처리가 안됐음. 
-> 200일 때는 setUser/ home 으로 redirect, 404일 때는 (user가 없을 때) headers:defaultHeaders post 로 신규 회원가입.  

로그인 흐름 다시 정리 
(1) firebase 로그인 후 IDToken을 받아온다
(2) GET ‘/user/me’ 로그인
404에러가 오면 ‘/users’ POST로 회원가입 처리
(3) 로그인 성공시 user데이터를 setUser 호출

**Comment by jieun-dev1** [comment]
1. 프론트 코드 수정 이후 병합 과정에서 백엔드 수정사항 

(1) 로그인 시 처음에 프론트 - 백엔드 연결 이슈 
프론트에서 요청을 보내도 백엔드 서버로 요청이 닿지 않는 이슈.  처음에는 백엔드 로직에 누락사항이 있는 줄 알았는데, 알고 보니 CORS 문제였네요. 
-localhost:8080(스프링) localhost:3000 (react)가 통신하면 CORS( cross-origin requests) 가 발생하기 때문에, package.json에서 아래 프록시 설정을 해줬습니다.  
"proxy":"http://localhost:8080" 

(2) 신규 가입 POST  
-기존 JWT Filter 코드에서는, DB 에 없는 유저접근 시 (신규 가입 되어야 하는) try catch 문으로 UsernameNotFoundException 에러를 401로 처리를 했었습니다. 리소스를 찾지 못하는 것이니 404가 더 적합해서 404로 변경하였습니다. (프론트에서 404로 보내주었으니 404로 변경해야 하기도 합니다) 

#정리 

해결: 로컬 테스트 GET /POST (신규가입) 모두 성공한 것 확인하였습니다. 
**미해결: logout 을 눌렀을 때, 로그인이 한 번 더 진행됩니다. 이 부분은 해결 필요합니다.** 로그아웃은 프론트에서 토큰 삭제하는 것으로 알고 있는데 해결되면 업데이트 부탁드려요. 백엔드에서 필요한 부분이 있으면 알려주세요. @searchme86 

2. 추후 작업 
(1) @searchme86 해당 Proxy 코드 추가해서 commit 하겠습니다. @dy-shin 현재 백엔드 코드 변경은 바로 develop으로 머지하겠습니다. (exception 만 추가되어서요!) 이견 있으면 말씀해주세요~ 

(2) 현재 로컬 테스트 환경은 성공했으니, 저는 HEROKU 배포 버전으로 옮기는 작업 하겠습니다. 이후 마이페이지 등 구현 작업 이어가겠습니다. 

*to do: 추후 권한이 있어야만 가능한 기능을 구현하려면, local storage에 token 을 저장하고, 로그아웃하면 삭제하는 로직을 추가하는 얘기를 어제 했었는데요 (https://github.com/Couch-Coders/6th-music-fe/issues/2) 글 api 합치기 전에 이 작업이 될 필요가 있을 것 같아요. @searchme86 @dy-shin  어떠세요?

**Comment by vel1024** [comment]
heroku 배포 버전으로 옮기면 cors 설정도 배포 url 에 맞게 재수정되어야 할 거 같습니다

**Comment by jieun-dev1** [comment]
아 그렇네요. 그 부분 공부해보고 다시 공유드릴게요.
